DROP TABLE IF EXISTS TB_DEFEITOS;
DROP TABLE IF EXISTS TB_PECAS;
DROP TABLE IF EXISTS TB_DEFEITOS_PECAS;
DROP TABLE IF EXISTS TB_VEICULOS;

-- DEFEITOS --
CREATE TABLE TB_DEFEITOS (
  nome VARCHAR(250) NOT NULL,
  id INTEGER NOT NULL
);

INSERT INTO TB_DEFEITOS (nome, id) VALUES
  ('Ferrugem', 1);
  
-- PECAS --
CREATE TABLE TB_PECAS (
  nome VARCHAR(250) NOT NULL,
  id INTEGER NOT NULL
);

INSERT INTO TB_PECAS (nome, id) VALUES
  ('Motor', 1);
  
-- DEFEITOS E PECAS --
CREATE TABLE TB_DEFEITOS_PECAS (
  idDefeitos INTEGER NOT NULL,
  idPecas INTEGER NOT NULL
);

INSERT INTO TB_DEFEITOS_PECAS (idPecas, idDefeitos) VALUES
  (1 , 1);